### PR TITLE
Combine data

### PR DESCRIPTION
**Pull request by Grant-diane**

### CODE REVIEW

**Comment by mlebiedzinski** [comment]
👎

**Review by spencermendelsohn — CHANGES_REQUESTED** [review]
NOOOOO

**Comment by P4rz1val22** [comment]
hell naw

**Comment by Estabrooks-m** [comment]
🧷

**Comment by spencermendelsohn** [comment]
image

**Comment by owens1127** [comment]
LGTM 🚀

**Comment by P4rz1val22** [comment]
🦑

**Review by spencermendelsohn — APPROVED** [review]

**Review by mlebiedzinski — APPROVED** [review]

**Comment by mlebiedzinski** [comment]
cool

**Pull request merged**
